routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/login', function () {
//    return view('admin.layout.login');
//});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


Route::group(array('prefix' => '/', 'as' => 'website.', 'namespace' => 'website'), function () {

    Route::get('/', 'indexController@index')->name('index');
    Route::get('/singleAlbum/{id}', 'indexController@singleAlbum')->name('singleAlbum');
    Route::get('/myAlbums/{id}', 'indexController@myAlbums')->name('myAlbums');
    Route::get('/profile/{id}', 'indexController@profile')->name('profile');

    Route::post('/update-profile/{id}', 'indexController@UpdateProfile')->name('UpdateProfile');
    Route::post('/addAlbum', 'indexController@addAlbum')->name('addAlbum');

    Route::delete('/deleteAlbum/{id}', 'indexController@deleteAlbum')->name('deleteAlbum');
    Route::get('/Album/{id}', 'indexController@editAlbum')->name('editAlbum');
    Route::post('/update/{id}', 'indexController@update')->name('update');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(array('prefix' => 'dashboard','as'=>'admin.' ,'middleware' => ['auth','admin'], 'namespace' => 'admin'), function() {

    Route::get('/', 'indexController@index')->name('layout.main');
    Route::resource('users', 'userController');
    Route::resource('albums', 'albumController');
    Route::resource('roles','roleController');

});

app/Http/Controllers/website/indexController.php
<?php

namespace App\Http\Controllers\website;

use App\Album;
use App\Banner;
use App\CartItem;
use App\Category;
use App\Contact;
use App\Contacts;
use App\Donate;
use App\Firm;
use App\Gallery;
use App\Offer;
use App\Payment;
use App\Post;
use App\Product;
use App\Service;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class indexController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index()
    {
        $albums=Album::where('status','general')->paginate(12);
        return view('website.index',compact('albums'));
    }



    public function singleAlbum($id)
    {
        $album=Album::findOrFail($id);
        return view('website.singleAlbum',compact('album'));
    }



    public function myAlbums($id)
    {
        $allAlbums=Album::where('user_id',$id)->get();

        return view('website.myAlbums',compact('allAlbums'));
    }

    public function profile()
    {

        return view('website.profile');
    }



    public function UpdateProfile(Request $request, $id)
    {

        $user=User::find($id);
        $inputs = $request->all();

        if($request->password != null) {$user->update(['password'=>bcrypt($request->password),]);}
        $user->update(array_except($inputs,['password']));

        alert()->success('تم  تعديل البيانات بنجاح !')->autoclose(5000);
        return back();

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function addAlbum(Request $request)
    {
        $this->validate($request,[
            'name'=>'required|string|',
            'images' => 'required|array',
            'image'=>'required|image',
            'user_id'=>'required|numeric|exists:users,id',

        ]);
        $inputs=$request->all();
        if($request->hasFile('image')) {
            $image = uploader($request->image, 'photos');
            $inputs['image']=$image;
        }
        $album=Album::create($inputs);
        if ($request->hasFile('images')) {
            multiUploader($request, 'images', new Gallery(),$onId = null ,$album->id);
        }

        $albums=Album::where('user_id',auth()->id())->get();


        return response()->json(['album'=>view('website.album',compact('album'))->render()]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function deleteAlbum($id)
    {
        $album=Album::find($id);

        $album->delete();
        alert()->success('Album Deleted sucessfully');
        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function editAlbum($id)
    {
        $album=Album::findOrFail($id);
        return view('website.editAlbum',compact('album'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $album=Album::findOrFail($id);
       // dd($request->all());
        $this->validate($request,[
            'name'=>'required|string|',
            'images' => 'sometimes|array',

            'user_id'=>'required|numeric|exists:users,id',

        ]);
        $inputs=$request->all();
     //  dd($inputs);
        if($request->hasFile('image')) {
            $image = uploader($request->image, 'photos');
            $inputs['image']=$image;
        }

//        $inputs['user_id']=auth()->id();
        $album->update($inputs);
        if ($request->hasFile('images')) {
            $album  ->images()->delete();
            multiUploader($request, 'images', new Gallery(),$onId = null ,$album->id);
        }

        alert()->success('Album edit!')->autoclose(5000);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }



}

resources/views/website/album.blade.php
<?php
use Carbon\Carbon;
?>

<!-- Single Event Area -->

<div class=" col-12 col-md-6 col-lg-4">
        <div class="single-event-area mb-30">
            <div class="event-thumbnail">
                <img src="{{getimg($album->image)}}" alt="">
            </div>
            <div class="event-text">
                <h4>{{$album->name}}</h4>
                <div class="event-meta-data">
                    @if ($album->status=="general")
                        <a href="#" class="event-place">Public</a>
                    @else
                        <a href="#" class="event-place">Private</a>
                    @endif
                    <a href="#" class="event-date">{{Carbon::parse($album->created_at)->toFormattedDateString()}}</a>
                </div>
                <a href="#" class="btn see-more-btn">See Event</a>
            </div>
        </div>

</div>

resources/views/website/editAlbum.blade.php
@extends('layouts.master')
@section('styles')
@stop
@section('content')
    <!-- ##### Header Area End ##### -->

    <!-- ##### Breadcumb Area Start ##### -->
    <section class="breadcumb-area bg-img bg-overlay" style="background-image: url({{asset('website/img/bg-img/breadcumb3.jpg')}});">
        <div class="bradcumbContent">
            <p>See what’s new</p>
            <h2>edit my Album</h2>
        </div>
    </section>
    <!-- ##### Breadcumb Area End ##### -->



    <!-- ##### Newsletter & Testimonials Area Start ##### -->
    <section class="newsletter-testimonials-area">
        <div class="container">
            <div class="row">

                <!-- Newsletter Area -->
                <div class="col-12 col-lg-12">
                    <div class="newsletter-area mb-100">
                        <div class="section-heading text-left mb-50">
                            <p>See what’s new</p>
                            <h2>Subscribe to newsletter</h2>
                        </div>
                        <div class="newsletter-form">
                            <form id="form" method="post" action="{{route('website.update',$album->id)}}">
                                @csrf
                                @if (count($errors) > 0)
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <input type="hidden" name="user_id" value={{Auth::user()->id}}   >
                                <input type="text" name="name" id="newsletterSearch" placeholder="AlbumName" value="{{$album->name}}">
                              @if ($album->status=='general')
                                    <select name="status"  class="select" >
                                        <option>AlbumStatus</option>
                                        <option value="general" selected>Public</option>
                                        <option value="private">Private</option>
                                    </select>

                               @else
                                    <select name="status"  class="select" >
                                        <option>AlbumStatus</option>
                                        <option value="general" >Public</option>
                                        <option value="private" selected>Private</option>
                                    </select>

                                @endif

                                <span>*add general image to album</span>
                                <input type="file" name="image" >
                                <span>*add multiple images to album</span>
                                <input type="file" name="images[]" multiple >

                                <button type="submit" class="btn oneMusic-btn">Add Album <i class="fa fa-angle-double-right"></i></button>
                            </form>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </section>
@stop

resources/views/website/index.blade.php
@extends('layouts.master')
@section('styles')
@stop
@section('content')

    <!-- ##### Hero Area Start ##### -->
    <section class="hero-area">
        <div class="hero-slides owl-carousel">
            <!-- Single Hero Slide -->
            <div class="single-hero-slide d-flex align-items-center justify-content-center">
                <!-- Slide Img -->
                <div class="slide-img bg-img" style="background-image: url({{asset('website/img/bg-img/bg-1.jpg')}});"></div>
                <!-- Slide Content -->
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="hero-slides-content text-center">
                                <h6 data-animation="fadeInUp" data-delay="100ms">Latest album</h6>
                                <h2 data-animation="fadeInUp" data-delay="300ms">Beyond Time <span>Beyond Time</span></h2>
                                <a data-animation="fadeInUp" data-delay="500ms" href="#" class="btn oneMusic-btn mt-50">Discover <i class="fa fa-angle-double-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Single Hero Slide -->
            <div class="single-hero-slide d-flex align-items-center justify-content-center">
                <!-- Slide Img -->
                <div class="slide-img bg-img" style="background-image: url({{asset('website/img/bg-img/bg-2.jpg')}});"></div>
                <!-- Slide Content -->
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="hero-slides-content text-center">
                                <h6 data-animation="fadeInUp" data-delay="100ms">Latest album</h6>
                                <h2 data-animation="fadeInUp" data-delay="300ms">Colorlib Music <span>Colorlib Music</span></h2>
                                <a data-animation="fadeInUp" data-delay="500ms" href="#" class="btn oneMusic-btn mt-50">Discover <i class="fa fa-angle-double-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Hero Area End ##### -->


    <section class="oneMusic-buy-now-area has-fluid bg-gray section-padding-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading style-2">
                        <p>See what’s new</p>
                        <h2>Buy What’s New</h2>
                    </div>
                </div>
            </div>

            <div class="row ">
           @foreach($albums as $album)
                <!-- Single Album Area -->
                <a href="{{route('website.singleAlbum',$album->id)}}">
                <div class="col-12 col-sm-6 col-md-4 col-lg-2">
                    <div class="single-album-area wow fadeInUp" data-wow-delay="100ms">
                        <div class="album-thumb">
                            <img src="{{getimg($album->image)}}" alt="">
                            <!-- Album Price -->

                            <!-- Play Icon -->

                        </div>
                        <div class="album-info">
                            <a href="#">
                                <h5>{{$album->name}}</h5>
                            </a>
                            <p>Radio Station</p>
                        </div>
                    </div>
                </div>
                </a>
            @endforeach

            </div>

            <div class="row">
                <div class="col-12">
                    <div class="load-more-btn text-center wow fadeInUp" data-wow-delay="300ms">
                        <a href="#" class="btn oneMusic-btn">Load More <i class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Buy Now Area End ##### -->


    @stop

resources/views/website/login.blade.php
@extends('layouts.master')
@section('styles')
@stop
@section('content')

<!-- ##### Breadcumb Area Start ##### -->
<section class="breadcumb-area bg-img bg-overlay" style="background-image: url({{asset('website/img/bg-img/breadcumb3.jpg')}});">
    <div class="bradcumbContent">
        @if (auth()->check())

            <h3>{{ Auth::user()->name }} </h3>
        @endif
        <h2>Login</h2>
    </div>
</section>
<!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Login Area Start ##### -->
    <section class="login-area section-padding-100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-8">
                    <div class="login-content">
                        @if (auth()->check())

                        <h3>{{ Auth::user()->name }} </h3>
                        @endif
                        <!-- Login Form -->
                        <div class="login-form">
                            <form action="{{ route('login') }}" method="post">
                                @csrf
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email address</label>
                                    <input type="email"  name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter E-mail">
                                    <small id="emailHelp"  class="form-text text-muted"><i class="fa fa-lock mr-2"></i>We'll never share your email with anyone else.</small>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password</label>
                                    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                                </div>
                                <button type="submit" class="btn oneMusic-btn mt-30">Login</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Login Area End ##### -->

@stop

resources/views/website/myAlbums.blade.php
@extends('layouts.master')
@section('styles')
@stop
@section('content')
    <!-- ##### Header Area End ##### -->

    <!-- ##### Breadcumb Area Start ##### -->
    <section class="breadcumb-area bg-img bg-overlay" style="background-image: url({{asset('website/img/bg-img/breadcumb3.jpg')}});">
        <div class="bradcumbContent">
            <p>See what’s new</p>
            <h2> My Albums</h2>
        </div>
    </section>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Events Area Start ##### -->
    <section class="events-area section-padding-100">
        <div class="container">
            <div class="row album">

                <?php
                use Carbon\Carbon;
                ?>

                <!-- Single Event Area -->
                    @foreach($allAlbums as $album)
                        <a href="{{route('website.singleAlbum',$album->id)}}">
                        <div class="col-12 col-md-6 col-lg-4">
                            <div class="single-event-area mb-30">
                                <div class="event-thumbnail">
                                    <img src="{{getimg($album->image)}}" alt="">
                                </div>
                                <div class="event-text">
                                    <h4>{{$album->name}}</h4>
                                    <div class="event-meta-data">
                                        @if ($album->status=="general")
                                            <a href="#" class="event-place">Public</a>
                                        @else
                                            <a href="#" class="event-place">Private</a>
                                        @endif
                                        <a href="#" class="event-date">{{Carbon::parse($album->created_at)->toFormattedDateString()}}</a>
                                    </div>
                                    <a href="{{route("website.editAlbum",$album->id)}}" class="btn btn-primary btn-circle" > edit</a>

                                    <a href="#" class="btn btn-danger btn-circle" onclick="Delete({{$album->id}})" > delete</a>

                                    {!!Form::open( ['route' => ['website.deleteAlbum',$album->id] ,'id'=>'delete-form'.$album->id, 'method' => 'Delete']) !!}
                                    {!!Form::close() !!}
                                </div>
                            </div>
                        </div>
                        </a>
                    @endforeach



            </div>

            <div class="row">
                <div class="col-12">
                    <div class="load-more-btn text-center mt-70">
                        <a href="#" class="btn oneMusic-btn">Load More <i class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Events Area End ##### -->

    <!-- ##### Newsletter & Testimonials Area Start ##### -->
    <section class="newsletter-testimonials-area">
        <div class="container">
            <div class="row">

                <!-- Newsletter Area -->
                <div class="col-12 col-lg-12">
                    <div class="newsletter-area mb-100">
                        <div class="section-heading text-left mb-50">
                            <p>See what’s new</p>
                            <h2>Subscribe to newsletter</h2>
                        </div>
                        <div class="newsletter-form">
                            <form id="form">
                                @csrf
                                <input type="hidden" name="user_id" value={{Auth::user()->id}}   >
                                <input type="text" name="name" id="newsletterSearch" placeholder="AlbumName">
                                <select name="status"  class="select"  >
                                    <option>AlbumStatus</option>
                                    <option value="general">Public</option>
                                    <option value="private">Private</option>
                                </select>
                                <span>*add general image to album</span>
                                <input type="file" name="image" >
                                <span>*add multiple images to album</span>
                                <input type="file" name="images[]" multiple >

                                <button type="submit" class="btn oneMusic-btn">Add Album <i class="fa fa-angle-double-right"></i></button>
                            </form>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </section>
@stop

@section('footer')
<script>

    $("#form").submit(function(e) {
        e.preventDefault();
        var form = $(this);
        var formData = new FormData(form[0]);

        $.ajax({
            type: "POST",
            url: '{{route('website.addAlbum')}}',
            data: formData,
            contentType: false,
            processData: false,

            success: function (data) {


                $('.album').append(data.album)

            }


        })

    });


    function Delete(id) {
        var item_id=id;
        console.log(item_id);
        swal({
            title: " ",
            text: "Do you  want  to delete this Album ?",
            icon: "warning",
            buttons: ["cancel", "yes"],
            dangerMode: true,

        }).then(function(isConfirm){
            if(isConfirm){
                document.getElementById('delete-form'+item_id).submit();
            }
            else{
                swal("Canceled", "deleting canceled",'info',{buttons:'yes'});
            }
        });
    }
</script>
    @stop

resources/views/website/profile.blade.php
@extends('layouts.master')
@section('styles')
@stop
@section('content')

    <!-- ##### Breadcumb Area Start ##### -->
    <section class="breadcumb-area bg-img bg-overlay" style="background-image: url({{asset('website/img/bg-img/breadcumb.jpg')}});">
        <div class="bradcumbContent">

        </div>
    </section>
    <!-- ##### Breadcumb Area End ##### -->



    <!-- ##### Contact Area Start ##### -->
    <section class="contact-area section-padding-0-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading">
                        <p>See what’s new</p>
                        <h2>My Profile</h2>
                    </div>
                </div>
            </div>

            <div class="row profile" >
                <div class="col-12">
                    <!-- Contact Form Area -->
                    <div class="contact-form-area">
                        {!!Form::model(auth()->user() , ['route' => ['website.UpdateProfile' , auth()->id()] ,'class'=>'form','method' => 'POST','files'=>true]) !!}
                            <div class="row">
                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        {!! Form::text("name",null,['class'=>'form-control','id'=>'name','placeholder'=>'name'])!!}
                                    </div>
                                </div>
                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        {!! Form::email("email",null,['class'=>'form-control','id'=>'email','placeholder'=>'email'])!!}
                                    </div>
                                </div>
                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        {!! Form::text("phone",null,['class'=>'form-control','id'=>'phone','placeholder'=>'phone'])!!}

                                    </div>
                                </div>
                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        {!! Form::password("password",['class'=>'form-control','placeholder'=>'new password'])!!}
                                    </div>
                                </div>

                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        {!! Form::password("password_confirmation",['class'=>'form-control','placeholder'=>'rewrite new password'])!!}
                                    </div>
                                </div>
                                <div class="col-12 text-center">
                                    <button class="btn oneMusic-btn mt-30" type="submit">Update <i class="fa fa-angle-double-right"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Contact Area End ##### -->
@stop

resources/views/website/register.blade.php
@extends('layouts.master')
@section('styles')
@stop
@section('content')

<!-- ##### Breadcumb Area Start ##### -->
<section class="breadcumb-area bg-img bg-overlay" style="background-image: url(img/bg-img/breadcumb3.jpg);">
    <div class="bradcumbContent">
        <p>See what’s new</p>
        <h2>Login</h2>
    </div>
</section>
<!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Login Area Start ##### -->
    <section class="login-area section-padding-100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-8">
                    <div class="login-content">
                        <h3>Welcome Back</h3>
                        <!-- Login Form -->
                        <div class="login-form">
                            <form action="{{route('register')}}" method="post">
                                @csrf

                                <div class="form-group">
                                    <label for="name">UserName</label>
                                    <input type="text" name="name" class="form-control" id="name"   placeholder="Enter Name">
                                </div>
                                <div class="form-group">
                                    <label for="phone">phone</label>
                                    <input type="text" name="phone" class="form-control" id="phone"   placeholder="Enter phone">
                                </div>

                                <div class="form-group">
                                    <label >Email address</label>
                                    <input type="email" class="form-control" name="email"  placeholder="Enter E-mail">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password</label>
                                    <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
                                </div>
                                <div class="form-group">
                                    <label for="passwordcofirm">password Confirmation</label>
                                    <input type="password" class="form-control" name="password_confirmation" id="passwordcofirm" aria-describedby="emailHelp" placeholder="Re-enter password">
                                </div>
                                <button type="submit" class="btn oneMusic-btn mt-30">Register</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Login Area End ##### -->

@stop