routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/login', function () {
//    return view('admin.layout.login');
//});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


Route::group(array('prefix' => '/', 'as' => 'website.', 'namespace' => 'website'), function () {

    Route::get('/', 'indexController@index')->name('index');
    Route::get('/singleAlbum/{id}', 'indexController@singleAlbum')->name('singleAlbum');
    Route::get('/myAlbums/{id}', 'indexController@myAlbums')->name('myAlbums');
    Route::get('/profile/{id}', 'indexController@profile')->name('profile');

    Route::post('/update-profile/{id}', 'indexController@UpdateProfile')->name('UpdateProfile');
    Route::post('/addAlbum', 'indexController@addAlbum')->name('addAlbum');

    Route::delete('/deleteAlbum/{id}', 'indexController@deleteAlbum')->name('deleteAlbum');
    Route::get('/Album/{id}', 'indexController@editAlbum')->name('editAlbum');
    Route::post('/update/{id}', 'indexController@update')->name('update');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(array('prefix' => 'dashboard','as'=>'admin.' ,'middleware' => ['auth','admin'], 'namespace' => 'admin'), function() {

    Route::get('/', 'indexController@index')->name('layout.main');
    Route::resource('users', 'userController');
    Route::resource('albums', 'albumController');
    Route::resource('roles','roleController');

});

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>One Music - Modern Music HTML5 Template</title>

    <!-- Favicon -->
    <link rel="icon" href="{{asset('website/img/core-img/favicon.ico')}}">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{{asset('website/style.css')}}">

</head>

<body>
<!-- Preloader -->
<div class="preloader d-flex align-items-center justify-content-center">
    <div class="lds-ellipsis">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>

<!-- ##### Header Area Start ##### -->
<header class="header-area">
    <!-- Navbar Area -->
    <div class="oneMusic-main-menu">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">
                <!-- Menu -->
                <nav class="classy-navbar justify-content-between" id="oneMusicNav">

                    <!-- Nav brand -->
                    <a href="index.blade.php" class="nav-brand"><img src="{{asset('website/img/core-img/logo.png')}}" alt=""></a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- Close Button -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">
                            <ul>
                                <li><a href="{{route('website.index')}}">Home</a></li>

                                </li>
                                @if (auth()->check())
                                    <li><a href="{{route('website.myAlbums',Auth::user()->id)}}">My Albums </a></li>
                                @endif

                            </ul>

                            <!-- Login/Register & Cart Button -->
                            <div class="login-register-cart-button d-flex align-items-center">
                                <!-- Login/Register -->
                                <div class="login-register-btn mr-50">
                                    @if (!auth()->check())
                                    <a href="{{route('login')}}" id="loginBtn">Login </a>
                                    <a href="{{route('register')}}" id="registerBtn"> Register</a>
                                    @endif
                                    @if (auth()->check())

                                    <a href="{{route('website.profile',Auth::user()->id)}}" id="logiBtn">{{Auth::user()->name}} </a>
                                        @endif
                                </div>

                                <!-- Cart Button -->
                                @if (auth()->check())
                                <div class="cart-btn">
                                    <a href="{{route('logout')}}" >Logout </a>
                                </div>
                                    @endif
                            </div>
                        </div>
                        <!-- Nav End -->

                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ##### Header Area End ##### -->


<!-- ********************************************** Content Area **************************************************** -->
@yield('content')
<!-- ********************************************** Content Area **************************************************** -->


<!-- ##### Footer Area Start ##### -->
<footer class="footer-area">
    <div class="container">
        <div class="row d-flex flex-wrap align-items-center">
            <div class="col-12 col-md-6">
                <a href="#"><img src="{{asset('website/img/core-img/logo.png')}}" alt=""></a>
                <p class="copywrite-text"><a href="#"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>

            <div class="col-12 col-md-6">
                <div class="footer-nav">
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Albums</a></li>
                        <li><a href="#">Events</a></li>
                        <li><a href="#">News</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- ##### Footer Area Start ##### -->



<!-- ##### All Javascript Script ##### -->
<!-- jQuery-2.2.4 js -->
<script src="{{asset('website/js/jquery/jquery-2.2.4.min.js')}}"></script>
<!-- Popper js -->
<script src="{{asset('website/js/bootstrap/popper.min.js')}}"></script>
<!-- Bootstrap js -->
<script src="{{asset('website/js/bootstrap/bootstrap.min.js')}}"></script>
<!-- All Plugins js -->
<script src="{{asset('website/js/plugins/plugins.js')}}"></script>
<!-- Active js -->
<script src="{{asset('website/js/active.js')}}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

@include('sweet::alert')
@yield('footer')
</body>

</html>